# Generated by Django 3.1.2 on 2020-10-15 17:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Facturacón'), ('4', 'Recaudación'), ('5', 'Sistemas'), ('6', 'Mantenimiento'), ('7', 'Otro')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
